import Head from 'next/head'
import { Inter } from '@next/font/google'



export default function Home() {
  return (
    <>
      <Head>
        <title>Matrimonial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1 className='text-3xl text-red-500' >
      Hello
     </h1>
     <h1 className='bg-primary '>Hello color</h1>
    </>
  )
}
